# Generated by Django 3.2.3 on 2021-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_test',
            field=models.BooleanField(default=False),
        ),
    ]
